import Link from "next/link";

export default function ListVenue() {
  return <main className="page-shell">
    <header className="site-header"><Link className="brand" href="/"><span className="brand-pin">●</span><span>venue<span>Find</span></span></Link><nav className="desktop-nav"><Link href="/venues">Discover</Link><Link href="/how-it-works">How it works</Link><Link href="/list-venue">For venue owners</Link></nav><Link className="button button-small button-outline" href="/venues">Discover venues</Link></header>
    <section className="page-hero"><p className="eyebrow">Venue partner pilot</p><h1>Help the right customers understand your space before they visit.</h1><p>Basic pilot listings are free. We verify the venue and its authorized contact before anything is published.</p></section>
    <div className="content-wrap"><div className="form-card"><h2>Register your interest</h2><p>This is the first step—not automatic publication. A VenueFind team member will contact you to complete verification.</p><form className="intake-grid"><label>Venue or business name<input name="venueName" required /></label><label>Your name<input name="contactName" required /></label><label>Phone / WhatsApp<input name="phone" type="tel" required /></label><label>Email, if available<input name="email" type="email" /></label><label>Area or community<input name="area" required /></label><label>Venue type<select name="type"><option>Event hall</option><option>Hotel event space</option><option>Restaurant private space</option><option>Garden or outdoor venue</option><option>Beach or resort venue</option><option>Community or multipurpose centre</option></select></label><label>Approximate maximum capacity<input name="capacity" type="number" min="1" /></label><label>Number of separately bookable spaces<input name="spaces" type="number" min="1" defaultValue="1" /></label><label className="full">Tell us briefly about the venue and the events you accept<textarea name="notes" /></label></form><div className="form-actions"><button className="button button-primary" type="button">Submit interest</button><small>Pilot intake is not yet live. This form currently demonstrates the agreed information flow.</small></div></div></div>
  </main>;
}
