import Link from "next/link";

export default function HowItWorks() {
  return <main className="page-shell">
    <header className="site-header"><Link className="brand" href="/"><span className="brand-mark">V</span><span>VenueFind</span></Link><nav className="desktop-nav"><Link href="/venues">Find venues</Link><Link href="/how-it-works">How it works</Link><Link href="/list-venue">For venue owners</Link></nav><Link className="button button-small button-outline" href="/list-venue">List your venue</Link></header>
    <section className="page-hero"><p className="eyebrow">A managed service, not just a directory</p><h1>We help you move from searching to a useful answer.</h1><p>VenueFind combines structured venue profiles with human confirmation through WhatsApp and telephone.</p></section>
    <div className="content-wrap"><ol className="steps"><li><span>1</span><div><h3>Describe the event</h3><p>Tell us the date, event type, expected guests, preferred areas and budget.</p></div></li><li><span>2</span><div><h3>Compare suitable venues</h3><p>See capacity, pricing information, facilities, restrictions, photos and date status.</p></div></li><li><span>3</span><div><h3>Request confirmation</h3><p>We contact the authorized venue representative when the date needs a fresh response.</p></div></li></ol><section className="status-explainer" style={{padding: 0}}><div className="section-intro compact"><p className="eyebrow">What the status means</p><h2>Honest answers are better than false certainty.</h2></div><div className="status-list"><article><span className="status-dot available"/><div><h3>Available — verified</h3><p>Recently confirmed. This does not reserve the venue.</p></div></article><article><span className="status-dot booked"/><div><h3>Booked</h3><p>The venue has reported the date as unavailable.</p></div></article><article><span className="status-dot required"/><div><h3>Confirmation required</h3><p>The information is missing, older, or waiting for a fresh response.</p></div></article></div></section></div>
  </main>;
}
